[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.dojah.io https://static.cloudflareinsights.com https://widget.dojah.io https://*.sentry.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.dojah.io https://fonts.gstatic.com https://identity.dojah.io; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com https://*.dojah.io https://identity.dojah.io; img-src 'self' data: blob: https:; connect-src 'self' https://api.dojah.io https://*.dojah.io https://static.cloudflareinsights.com https://*.supabase.co https://widget.dojah.io https://identity.dojah.io https://*.sentry.io; frame-src 'self' https://*.dojah.io https://identity.dojah.io; object-src 'none'; base-uri 'self'; form-action 'self';" 